<?php

return [
    'name'            => env('APP_NAME', 'AIRCARE'),
    'env'             => env('APP_ENV', 'local'),
    'debug'           => (bool) env('APP_DEBUG', true),
    'url'             => env('APP_URL', 'http://localhost'),
    'timezone'        => 'Asia/Jakarta',
    'locale'          => 'id',
    'fallback_locale' => 'en',
    'key'             => env('APP_KEY'),
    'cipher'          => 'AES-256-CBC',

    'providers' => [
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Notifications\NotificationServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,
        App\Providers\AppServiceProvider::class,
    ],

    'aliases' => [
        'App'     => Illuminate\Support\Facades\App::class,
        'Auth'    => Illuminate\Support\Facades\Auth::class,
        'DB'      => Illuminate\Support\Facades\DB::class,
        'Hash'    => Illuminate\Support\Facades\Hash::class,
        'Route'   => Illuminate\Support\Facades\Route::class,
        'Schema'  => Illuminate\Support\Facades\Schema::class,
        'Session' => Illuminate\Support\Facades\Session::class,
        'Storage' => Illuminate\Support\Facades\Storage::class,
        'Str'     => Illuminate\Support\Str::class,
        'URL'     => Illuminate\Support\Facades\URL::class,
        'View'    => Illuminate\Support\Facades\View::class,
    ],
];
